version: "3.8"

networks:
  artistry-network:
    name: artistry-network

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PRIVATE_PYPI_URL=${PRIVATE_PYPI_URL}
        - PRIVATE_PYPI_USER=${PRIVATE_PYPI_USER}
        - PRIVATE_PYPI_PASS=${PRIVATE_PYPI_PASS}
    image: artists_api:0.1.0
    command: bash /app/docker-entrypoint.sh
    ports:
      - 8080:8080
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_KEY: ${OPENAI_KEY}
      OPENAI_PROJECT: ${OPENAI_PROJECT}
      MONGODB_URI: ${MONGODB_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - artistry-network

  web:
    build: ./frontend
    image: artists_web:0.1.0
    command: bash /app/docker-entrypoint.sh
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: http://api:8080
    depends_on:
      - api
    networks:
      - artistry-network
